# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2026, 1202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupResnet101 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupResnet101.setGeometry(QtCore.QRect(50, 60, 341, 1111))
        self.groupResnet101.setObjectName("groupResnet101")
        self.pushButtonShowTrainImages = QtWidgets.QPushButton(self.groupResnet101)
        self.pushButtonShowTrainImages.setGeometry(QtCore.QRect(30, 230, 281, 51))
        self.pushButtonShowTrainImages.setObjectName("pushButtonShowTrainImages")
        self.pushButtonShowDataAugmentation = QtWidgets.QPushButton(self.groupResnet101)
        self.pushButtonShowDataAugmentation.setGeometry(QtCore.QRect(30, 590, 281, 51))
        self.pushButtonShowDataAugmentation.setObjectName("pushButtonShowDataAugmentation")
        self.pushButtonShowModelStructure = QtWidgets.QPushButton(self.groupResnet101)
        self.pushButtonShowModelStructure.setGeometry(QtCore.QRect(30, 410, 281, 51))
        self.pushButtonShowModelStructure.setObjectName("pushButtonShowModelStructure")
        self.pushButtonShowAccuracyAndLoss = QtWidgets.QPushButton(self.groupResnet101)
        self.pushButtonShowAccuracyAndLoss.setGeometry(QtCore.QRect(30, 770, 281, 51))
        self.pushButtonShowAccuracyAndLoss.setObjectName("pushButtonShowAccuracyAndLoss")
        self.pushButtonShowInference = QtWidgets.QPushButton(self.groupResnet101)
        self.pushButtonShowInference.setGeometry(QtCore.QRect(30, 950, 281, 51))
        self.pushButtonShowInference.setObjectName("pushButtonShowInference")
        self.pushButtonLoadImage = QtWidgets.QPushButton(self.groupResnet101)
        self.pushButtonLoadImage.setGeometry(QtCore.QRect(30, 60, 281, 51))
        self.pushButtonLoadImage.setObjectName("pushButtonLoadImage")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(530, 200, 1301, 981))
        self.photo.setText("")
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.textArea = QtWidgets.QLabel(self.centralwidget)
        self.textArea.setGeometry(QtCore.QRect(530, 60, 1301, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.textArea.setFont(font)
        self.textArea.setText("")
        self.textArea.setTextFormat(QtCore.Qt.AutoText)
        self.textArea.setAlignment(QtCore.Qt.AlignCenter)
        self.textArea.setObjectName("textArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2022 CvDl Hw1_05"))
        self.groupResnet101.setTitle(_translate("MainWindow", "5. Resnet101 Test"))
        self.pushButtonShowTrainImages.setText(_translate("MainWindow", "1. Show Train Images"))
        self.pushButtonShowDataAugmentation.setText(_translate("MainWindow", "3. Show Data Augmentation"))
        self.pushButtonShowModelStructure.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.pushButtonShowAccuracyAndLoss.setText(_translate("MainWindow", "4. Show Accuracy and Loss"))
        self.pushButtonShowInference.setText(_translate("MainWindow", "5. Inference"))
        self.pushButtonLoadImage.setText(_translate("MainWindow", "Load Image"))
